---
micronaut:
  application:
    name: message-service
  server:
    port: 8081
---
kafka:
  bootstrap:
    servers: 104.248.145.137:9092


#tag::jpa[]
jpa:
  default:
    packages-to-scan:
      - 'message.service.domain'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
        show_sql: true
  maintokdis:
    packages-to-scan:
      - 'referral.code.domainx'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update
        show_sql: true
#end::jpa[]

#
#datasources:
#  default:
#    url: ${JDBC_URL:`jdbc:mysql://tokdis-development.cnnviypzj8mf.ap-southeast-1.rds.amazonaws.com:3306/tokdis_rfc?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false`}
#    username: ${JDBC_USER:api_tokdis_payment}
#    password: ${JDBC_PASSWORD:%Ap1TDpAym3,%}
#    driverClassName: ${JDBC_DRIVER:com.mysql.jdbc.Driver}
#    maximum-pool-size: 2
#  maintokdis:
#    url: ${JDBC_URL:`jdbc:mysql://tokdis-development.cnnviypzj8mf.ap-southeast-1.rds.amazonaws.com:3306/tokdis?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false`}
#    username: ${JDBC_USER:api_tokdis}
#    password: ${JDBC_PASSWORD:%Ap1TDr3AD.T%}
#    driverClassName: ${JDBC_DRIVER:com.mysql.jdbc.Driver}
#    maximum-pool-size: 2

datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://103.36.32.148:3020/tokdis_rfc?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false`}
    username: ${JDBC_USER:broker}
    password: ${JDBC_PASSWORD:SemutBroker123}
    driverClassName: ${JDBC_DRIVER:com.mysql.jdbc.Driver}
    maximum-pool-size: 2
  maintokdis:
    url: ${JDBC_URL:`jdbc:mysql://103.36.32.148:3020/tokdis?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false`}
    username: ${JDBC_USER:broker}
    password: ${JDBC_PASSWORD:SemutBroker123}
    driverClassName: ${JDBC_DRIVER:com.mysql.jdbc.Driver}
    maximum-pool-size: 2